### ISSUE TITLE
ssh: connect to host <IP> port 22: Connection refused

### ISSUE THREAD

**Issue by bryanbocao** [BryanBo-Cao/quick-cheatsheets#16]

**Comment by bryanbocao** [comment]
Uncomment or append the line
```
Port 22
```
In the server:
```
sudo vim /etc/ssh/sshd_config
```

**Comment by Azzzzzz-7** [comment]
ssh: connect to host github.com port 22: Connection refused
Please help me！Thank you vrey much！
![Uploading 4d5baf0a6f8b94c600a6b685260633a.png…]()
![Uploading 8d1004018365cc62999bdd2bc7e0b13.png…]()

**Comment by bryanbocao** [comment]
@Az333333 Sorry, the image does not show up. It looks like you are trying to ssh to github.com. Can you tell us the specific things you did?

**Comment by Azzzzzz-7** [comment]
老师，我看了您的简历，所以我就用汉语了。我是在使用ssh公钥连接github时，一直连接不上。后来，我得知是我的ip问题，我换了梯子之后，问题就得到了解决。非常感谢您能回复我。

**Comment by bryanbocao** [comment]
> 老师，我看了您的简历，所以我就用汉语了。我是在使用ssh公钥连接github时，一直连接不上。后来，我得知是我的ip问题，我换了梯子之后，问题就得到了解决。非常感谢您能回复我。

@Azzzzzz-7 好的。
